name: Auto Create Codespace Whenever a New Branch Created

on:
  create:
    branches:
      - '**'

jobs:
  create-codespace:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug list files
        run: ls -R

      - name: Make script executable
        run: chmod +x script/create_codespace.sh

      - name: Create Codespace
        env:
          TOKEN: ${{ secrets.CODESPACE_PAT }}
        run: |
          ./script/create_codespace.sh \
            "${{ github.repository }}" \
            "${{ github.ref_name }}" \
            "$TOKEN" \
            "standardLinux32gb"
